// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package database

import (
	"context"
)

const addFeed = `-- name: AddFeed :one
INSERT INTO feeds ( 
    created_at, updated_at, name, url
    ) VALUES (
    current_timestamp,
    current_timestamp,
    ?,
    ?
)
RETURNING id, created_at, updated_at, name, url, last_fetched_at
`

type AddFeedParams struct {
	Name string
	Url  string
}

func (q *Queries) AddFeed(ctx context.Context, arg AddFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, addFeed, arg.Name, arg.Url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.LastFetchedAt,
	)
	return i, err
}
